name: Code Scan
on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

jobs:
    detect-duplicate-actions:
        uses: ./.github/workflows/detect-duplicate-actions.yml
    gitleaks:
        name: gitleaks
        needs: detect-duplicate-actions
        if: ${{ needs.detect-duplicate-actions.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
              with:
                  fetch-depth: 0
            - uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITLEAKS_NOTIFY_USER_LIST: '@elijaholmos'
