name: Check License Headers

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    detect-duplicate-actions:
        uses: ./.github/workflows/detect-duplicate-actions.yml
    check-license-headers:
        name: check-license-headers
        needs: detect-duplicate-actions
        if: ${{ needs.detect-duplicate-actions.outputs.should_skip != 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code (Non-PR)
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
              if: ${{ github.event_name != 'pull_request' }}
            - name: Checkout Code (PR)
              uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
              if: ${{ github.event_name == 'pull_request' }}
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}
            - name: Fix License Header
              uses: apache/skywalking-eyes/header@main
              with:
                  mode: fix
                  log: info
                  config: .github/config/.licenserc.yml
            - name: Push Changes
              uses: EndBug/add-and-commit@v9
              with:
                  message: 'chore(license): add license header to files'
                  default_author: github_actions
